Table count API added
covid-tracing-mongolia/backend-server pull request #6
Opened 2020-11-29 08:30 UTC by munkh-altai

Request example

curl --location --request GET 'https://key-submission.covidmongolia.app/api/count' \
--header 'Authorization: Bearer $token'

Response example {
"CountDiagnosisKeys": 0,
"CountEncryptionKeys": 1,
"CountEvents": 3,
"CountFailedKeyClaimAttempts": 0,
"CountTekUploadCount": 0
}

2020-11-29 09:22 UTC, amarbayar commented on pkg/server/keyclaim.go
> +	data["CountTekUploadCount"] = CountTekUploadCount
DB taldaa aldaa zaaval `-1, err` gesen response butsaaj baigaa yum baina. `err` gedgiig ni ter chigeer ni ene dictionary ruu onooj uguhuur json.Marshal hiij chadah bolovuu esvel `err` ni json.Marshal hiihed butetsiin zuruu garaad aldaa garaad yu ch butsaaj chadahaa bolichih bolu? Defensive baidlaar uursduu yag json boldog err butsaaj, onooj ugvul zugeer bolov uu.

2020-11-29 09:26 UTC, amarbayar commented
Thanks! @munkh-altai  -- CI test iig ni haraad uguh bolomj baina uu? Shineer nemsen method uudad test baihgui bolhoor fail-dsen baih shig bna. https://github.com/covid-tracing-mongolia/backend-server/pull/6/checks?check_run_id=1469416742

2020-12-03 06:27 UTC, s4kh requested changes

2020-12-03 06:27 UTC, s4kh commented on pkg/server/keyclaim.go
> +	CountDiagnosisKeys, _ := s.db.CountDiagnosisKeys()
end hervee err bwal default butsaah uu?
```
CountDiagnosisKeys, err := s.db.CountDiagnosisKeys()
if err != nil {
  log(ctx, err).Error('Sadly error occurred')
  CountDiagnosisKeys = 0 // something like this
}
```

2020-12-03 06:27 UTC, s4kh commented on pkg/server/keyclaim.go
> +	CountDiagnosisKeys, _ := s.db.CountDiagnosisKeys()
Busad endpoint deeree ingej shiidsen yum bna
```
if err != nil {
  log(ctx, err).Error("error counting db values")
  http.Error(w, "server error", http.StatusInternalServerError)
  return
}
```

2020-12-03 07:13 UTC, s4kh commented on pkg/server/keyclaim.go
> +	data["CountTekUploadCount"] = CountTekUploadCount
2 value return hiij bgaa bolohoor aldaa garwal utga ni -1 bolood json marshal deer bol aldaa garahgui bh.
`CountDiagnosisKeys, _ := s.db.CountDiagnosisKeys()` awch bgaa bolohoor err-oo( `_` ni err) eruusuu ashiglahgui bgaa.

2020-12-07 01:32 UTC, merged